LocalLibrary/LocalLibrary/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

LocalLibrary/catalog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from catalog import views
from users import views as user_views
urlpatterns = [
    path('', views.index, name='home'),
    path('home/', views.index, name='home'),
    path("books/", views.BookListView.as_view(), name="books"),
    path("books/<int:pk>/", views.BookDetailView.as_view(), name="book_detail"),
    path("author/", views.AuthorListView.as_view(), name="author"),
    path("author/<int:pk>/", views.AuthorDetailView.as_view(), name="author_detail"),
    path("register/", user_views.register, name="register"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("myborrowed/", views.UserBorrowedListView.as_view(), name="user_borrowed"),
    path("librarian/", views.Librarian.as_view(), name="librarian"),
    path("book/<uuid:pk>/renewal/", views.book_renewal_form, name="book_renewal"),

]

LocalLibrary/catalog/models.py
import datetime
import uuid
from django.contrib import admin
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.


class Author(models.Model):
    first_name = models.CharField(
        "First Name", max_length=100, help_text="Enter Author's first name.")
    last_name = models.CharField(
        "Last Name", max_length=100, help_text="Enter Author's last name.")
    date_of_birth = models.DateField("Born")
    date_of_death = models.DateField("Died", null=True, blank=True)

    @property
    @admin.display(ordering='last_name', description="Author's Name")
    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse("author_detail", kwargs={"pk": self.pk})


class Genre(models.Model):
    name = models.CharField("Genre Name", max_length=200,
                            help_text="Enter a book genre (e.g. Science Fiction)")

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=200,
                            help_text="Enter a natural language name.")

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author, on_delete=models.RESTRICT)
    summary = models.TextField(
        max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, unique=True,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(
        Genre, help_text='Select a genre for this book')
    language = models.ForeignKey(
        Language, on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("book_detail", kwargs={"pk": self.pk})


class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey(Book, on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(
        User, blank=True, null=True, on_delete=models.SET_NULL)
    LOAN_STATUS = (
        ('a', 'Available'),
        ('m', 'Maintenance'),
        ('r', 'Reserved'),
        ('o', 'On Loan')
    )
    status = models.CharField(max_length=1, choices=LOAN_STATUS,
                              blank=True, default='m', help_text='Book availability')

    @property
    def is_overdue(self):
        if self.due_back and datetime.date.today() > self.due_back:
            return True
        return False

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        return self.book.title

LocalLibrary/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'catalog/style.css' %}">
    <title>{% block title %}{% endblock title %}</title>
</head>

<body>
    <nav>
        <ul class="nav">
            <div class="nav-item-left rl">
                <li class="nav-item"><a href="{% url 'home' %}">Home</a></li>
                <li class="nav-item"><a href="{% url 'books' %}">Books</a></li>
                <li class="nav-item"><a href="{% url 'author' %}">Authors</a></li>
            </div>
            <div class="nav-item-right rl">
                {% if user.is_authenticated %}
                <div class="dropdown">
                    <button class="dropbtn nav-item ">{{ user.get_username }}</button>
                    <div class="dropdown-content">
                        <a class="nav-item" href="{% url 'user_borrowed' %}">Borrowed</a>
                    {% if perms.catalog.view_book %}
                    <a class="nav-item" href="{% url 'librarian' %}">Library</a>
                    {% endif %}
                        <a class="nav-item" href="{% url 'logout' %}">Logout</a>
                    </div>
                </div>
                {% else %}
                <li class="nav-item"><a href="{% url 'login' %}?next={{request.path}}">Login</a></li>
                {% endif %}
            </div>
        </ul>
    </nav>
    {% if messages %}
    {% for message in messages %}
    {{ message }}
    {% endfor %}
    {% endif %}
    {% block content %}{% endblock content %}
</body>

</html>