LocalLibrary/LocalLibrary/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

LocalLibrary/catalog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from catalog import views
from users import views as user_views
urlpatterns = [
    path('', views.index, name='home'),
    path('home/', views.index, name='home'),
    path("books/", views.BookListView.as_view(), name="books"),
    path("books/<int:pk>/", views.BookDetailView.as_view(), name="book_detail"),
    path("author/", views.AuthorListView.as_view(), name="author"),
    path("author/<int:pk>/", views.AuthorDetailView.as_view(), name="author_detail"),
    path("register/", user_views.register, name="register"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("myborrowed/", views.UserBorrowedListView.as_view(), name="user_borrowed"),
    path("librarian/", views.Librarian.as_view(), name="librarian"),
    path("book/<uuid:pk>/renewal/", views.book_renewal_form, name="book_renewal"),

]

LocalLibrary/catalog/models.py
import datetime
import uuid
from django.contrib import admin
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.


class Author(models.Model):
    first_name = models.CharField(
        "First Name", max_length=100, help_text="Enter Author's first name.")
    last_name = models.CharField(
        "Last Name", max_length=100, help_text="Enter Author's last name.")
    date_of_birth = models.DateField("Born")
    date_of_death = models.DateField("Died", null=True, blank=True)

    @property
    @admin.display(ordering='last_name', description="Author's Name")
    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse("author_detail", kwargs={"pk": self.pk})


class Genre(models.Model):
    name = models.CharField("Genre Name", max_length=200,
                            help_text="Enter a book genre (e.g. Science Fiction)")

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=200,
                            help_text="Enter a natural language name.")

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author, on_delete=models.RESTRICT)
    summary = models.TextField(
        max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, unique=True,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(
        Genre, help_text='Select a genre for this book')
    language = models.ForeignKey(
        Language, on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("book_detail", kwargs={"pk": self.pk})


class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey(Book, on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(
        User, blank=True, null=True, on_delete=models.SET_NULL)
    LOAN_STATUS = (
        ('a', 'Available'),
        ('m', 'Maintenance'),
        ('r', 'Reserved'),
        ('o', 'On Loan')
    )
    status = models.CharField(max_length=1, choices=LOAN_STATUS,
                              blank=True, default='m', help_text='Book availability')

    @property
    def is_overdue(self):
        if self.due_back and datetime.date.today() > self.due_back:
            return True
        return False

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        return self.book.title

LocalLibrary/users/models.py
from django.db import models

# Create your models here.

LocalLibrary/catalog/forms.py
from django import forms
import datetime
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
class BookRenewalForm(forms.Form):
    renewal_date = forms.DateField(
        label="Renewal Date:", help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data["renewal_date"]
        if data < datetime.date.today():
            raise ValidationError(_("Invalid date - renewal in past"))
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                _("Invalid date - renewal more than 4 weeks ahead"))
        return data

LocalLibrary/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username',
                  'email', 'password1', 'password2')

LocalLibrary/catalog/views.py
from dataclasses import field
import datetime
from .forms import BookRenewalForm
from django.http import HttpResponseRedirect
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView
from catalog.models import Author, Book, Language, Genre, BookInstance
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
# Create your views here.


def index(request):
    num_book = Book.objects.all().count()
    num_author = Author.objects.all().count()
    num_genre = Genre.objects.all().count()
    num_language = Language.objects.all().count()
    num_book_availabe = BookInstance.objects.filter(status='a').count()
    num_copies = BookInstance.objects.all().count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
    context = {
        'num_book': num_book,
        'num_author': num_author,
        'num_language': num_language,
        'num_genre': num_genre,
        'num_book_available': num_book_availabe,
        'num_copies': num_copies,
        'num_visits': num_visits
    }

    return render(request, 'catalog/index.html', context)


class BookListView(ListView):
    model = Book


class BookDetailView(DetailView):
    model = Book

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # book = Book.objects.get(pk=self.kwargs['pk'])
        # bookinst = BookInstance.objects.get(
        #     book=book)
        context['a'] = [b for b in BookInstance.objects.filter(
            book=Book.objects.get(pk=self.kwargs['pk'])) if b.status == 'a'][:1]
        context['d'] = [e for e in BookInstance.objects.filter(
            book=Book.objects.get(pk=self.kwargs['pk'])).order_by('due_back') if e.due_back and e.due_back < datetime.date.today() + datetime.timedelta(weeks=1)][:1]

        return context


class AuthorListView(ListView):
    model = Author


class AuthorDetailView(DetailView):
    model = Author


class UserBorrowedListView(LoginRequiredMixin, ListView):
    model = BookInstance

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

    template_name = "user/user_borrowed.html"


class Librarian(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = BookInstance
    permission_required = 'catalog.view_book'

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')

    template_name = "user/librarian.html"


@permission_required('catalog.view_book', )
def book_renewal_form(request, pk):
    """View function for renewing a specific BookInstance by librarian."""
    book_instance = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = BookRenewalForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('librarian'))

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = BookRenewalForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'user/book_renwal_form.html', context)

LocalLibrary/users/views.py
from django.shortcuts import redirect, render
from .forms import UserRegisterForm
from django.contrib import messages
# Create your views here.


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid:
            form.save()
        username = form.cleaned_data.get('username')
        messages.success(
            request, f'Welcome {username},You Account has been created! Now you can login.')
        return redirect('/')

    else:
        form = UserRegisterForm()
    return render(request, 'catalog/user_form.html', {'form': form})

LocalLibrary/templates/catalog/author_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{author.full_name}}{% endblock title %}
{% block content %}
<link rel="stylesheet" href="{% static 'catalog/author_detail.css' %}">
<link rel="stylesheet" href="{% static 'catalog/book_list.css' %}">
<div class="author">
<h2>{{author.full_name}}</h2>
<p>{{author.date_of_birth}} - {% if author.date_of_death %}{{author.date_of_death}}{% endif %}</p>
</div>

<div class="container">
    <h4>{{author.full_name}}'s Books</h4>
    <hr>
    <ul class='book-list'>
        {% for books in author.book_set.all %}
        <li class='book'>
            <a href="{{books.get_absolute_url}}">
                <img class='book-cover' src="https://source.unsplash.com/random/150x150?Book"
                    alt="{{book.title}} thumbnail">
                <div class="book-detail">
                    <a class="book-title" href="{{books.get_absolute_url}}">{{books.title}}</a>
                    <p class="book-subtitle"><small>By</small><a href="{{books.author.get_absolute_url}}"><em>
                                {{books.author.full_name}}</em></a></p>
                    <p class="book-subtitle"><small>{{books.bookinstance_set.all.count}}
                            Cop{{books.bookinstance_set.all.count|pluralize:'y,ies' }} Total</small></p>
                </div>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock content %}

LocalLibrary/templates/catalog/author_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Author{% endblock title %}
{% block content %}
<link rel="stylesheet" href="{% static 'catalog/author_list.css' %}">
<div class="content">

    {% for author in author_list %}
    <div class="container">
        <img class='profile' src="https://source.unsplash.com/random/150x150?author" alt="">
        <div class="info">
            <p><a href="{{author.get_absolute_url}}">{{author.full_name}}</a></p>
        </div>
    </div>
    {% endfor %}

</div>

{% endblock content %}

LocalLibrary/templates/catalog/book_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Book detail{% endblock title %}
{% block content %}
<link rel="stylesheet" href="{% static 'catalog/book_detail.css' %}">
<div class="content">
    <div class="container">
        <div class="left">
            <div ><img class="book-cover" src="https://source.unsplash.com/random?Books,Literature"
                alt="{{book.title}}'s cover"></div>
            <div class="detail">
                <p>Author: <small class="genre"><a class="author" href="{{book.author.get_absolute_url}}">{{book.author}}</a></small></p>
                <p>Language: <small class="genre">{{book.language}}</small> </p>
                <p>Genre: <small class="genre">{{book.genre.all|join:", "}} </small> </p>
                <p>Status: <small>{% if a %}<span style='color:green'>Available</span>{% else %} <span style='color:red'>{% if d %}{% for e in d %}Available in {{e.due_back}}{% endfor %}{% endif %}</span>{% endif %}</p></small>
            </div>
        </div>
        <div class="right">
            <p class="title"><strong>{{book.title}}</strong></p>
            <p class="sum">Summary:</p>
            <p class="summary">{{book.summary}}</p>
            {% for copy in book.bookinstance_set.all %}
            {% if  forloop.counter == 1 %}
            <p style='margin-top:5px;' ><small>{{copy.imprint}}</small></p>
            {% endif %}
            {% endfor %}
            
        </div>
    </div>
</div>
{% endblock content %}

LocalLibrary/templates/catalog/book_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Books{% endblock title %}
{% block content %}
<link rel="stylesheet" href="{% static 'catalog/book_list.css' %}">
<div class="container">
    <ul class='book-list'>
        {% for books in book_list %}
        <li class='book'>
            <a href="{{books.get_absolute_url}}">
                <img class='book-cover' src="https://source.unsplash.com/random/150x150?Book"
                    alt="{{book.title}} thumbnail">
                <div class="book-detail">
                    <a class="book-title" href="{{books.get_absolute_url}}">{{books.title}}</a>
                    <p class="book-subtitle"><small>By</small><a href="{{books.author.get_absolute_url}}"><em>
                                {{books.author.full_name}}</em></a></p>
                    <p class="book-subtitle"><small>{{books.bookinstance_set.all.count}}
                            Cop{{books.bookinstance_set.all.count|pluralize:'y,ies' }} Total</small></p>
                </div>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock content %}

LocalLibrary/templates/catalog/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock title %}
{% block content %}
<link rel="stylesheet" href="{% static 'catalog/index.css' %}">
<div class="container">
    <h1>The library has the following records</h1>
    <ul>
        <li><small>You visited this library {{num_visits}} time{{num_visits|pluralize}}</small></li>
        <li><Strong>Books:</Strong> {{num_book}}</li>
        <li><Strong>Author:</Strong> {{num_author}}</li>
        <li><Strong>Genre:</Strong> {{num_genre}}</li>
        <li><Strong>Copies:</Strong> {{num_copies}}</li>
        <li><Strong>Copies Availble:</Strong> {{num_book_available}}</li>
        <li><strong>Language:</strong> {{num_language}}</li>
    </ul>
</div>
{% endblock content %}

LocalLibrary/templates/catalog/user_form.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Sign in{% endblock title %}
{% block content %}
<link rel="stylesheet" href="{% static 'registration/login.css' %}">
<div class="container">
<form action="" method="post">
    {% csrf_token %}
    <fieldset>
        {{form|crispy}}
        <button type="submit">Sign up</button>
    <small class='sm'>Have an Account? <a class='sign' href="{% url 'login' %}">Log in</a></small>
    </fieldset>
</form>
</div>
{% endblock content %}