LocalLibrary/LocalLibrary/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

LocalLibrary/catalog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from catalog import views
from users import views as user_views
urlpatterns = [
    path('', views.index, name='home'),
    path('home/', views.index, name='home'),
    path("books/", views.BookListView.as_view(), name="books"),
    path("books/<int:pk>/", views.BookDetailView.as_view(), name="book_detail"),
    path("author/", views.AuthorListView.as_view(), name="author"),
    path("author/<int:pk>/", views.AuthorDetailView.as_view(), name="author_detail"),
    path("register/", user_views.register, name="register"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("myborrowed/", views.UserBorrowedListView.as_view(), name="user_borrowed"),
    path("librarian/", views.Librarian.as_view(), name="librarian"),
    path("book/<uuid:pk>/renewal/", views.book_renewal_form, name="book_renewal"),

]

LocalLibrary/catalog/models.py
import datetime
import uuid
from django.contrib import admin
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.


class Author(models.Model):
    first_name = models.CharField(
        "First Name", max_length=100, help_text="Enter Author's first name.")
    last_name = models.CharField(
        "Last Name", max_length=100, help_text="Enter Author's last name.")
    date_of_birth = models.DateField("Born")
    date_of_death = models.DateField("Died", null=True, blank=True)

    @property
    @admin.display(ordering='last_name', description="Author's Name")
    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse("author_detail", kwargs={"pk": self.pk})


class Genre(models.Model):
    name = models.CharField("Genre Name", max_length=200,
                            help_text="Enter a book genre (e.g. Science Fiction)")

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=200,
                            help_text="Enter a natural language name.")

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author, on_delete=models.RESTRICT)
    summary = models.TextField(
        max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, unique=True,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(
        Genre, help_text='Select a genre for this book')
    language = models.ForeignKey(
        Language, on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("book_detail", kwargs={"pk": self.pk})


class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey(Book, on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(
        User, blank=True, null=True, on_delete=models.SET_NULL)
    LOAN_STATUS = (
        ('a', 'Available'),
        ('m', 'Maintenance'),
        ('r', 'Reserved'),
        ('o', 'On Loan')
    )
    status = models.CharField(max_length=1, choices=LOAN_STATUS,
                              blank=True, default='m', help_text='Book availability')

    @property
    def is_overdue(self):
        if self.due_back and datetime.date.today() > self.due_back:
            return True
        return False

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        return self.book.title

LocalLibrary/users/models.py
from django.db import models

# Create your models here.

LocalLibrary/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username',
                  'email', 'password1', 'password2')

LocalLibrary/users/views.py
from django.shortcuts import redirect, render
from .forms import UserRegisterForm
from django.contrib import messages
# Create your views here.


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid:
            form.save()
        username = form.cleaned_data.get('username')
        messages.success(
            request, f'Welcome {username},You Account has been created! Now you can login.')
        return redirect('/')

    else:
        form = UserRegisterForm()
    return render(request, 'catalog/user_form.html', {'form': form})

LocalLibrary/templates/user/book_renwal_form.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Book Renewal{% endblock title %}
{% block content %}
<link rel="stylesheet" href="{% static 'registration/login.css' %}">
<style>
    legend{
        margin-bottom:8px;
        padding-left:0px;
    }
    br{
        margin: 6px;
    }
</style>
<div class="container">
    
<form action="" method="post">
    <legend>{{book_instance.book.title}}
        <br>
       <small>Due Back: <span {% if book_instance.is_overdue %} style='color:red;' {% else %}style='color:rgb(121, 202, 0)' {% endif %} >{{book_instance.due_back}}</span> </small> 
    </legend>
    {% csrf_token %}
        {{form|crispy}}
        <button type="submit">Renew</button>
</form>
</div>
{% endblock content %}

LocalLibrary/templates/user/librarian.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Books{% endblock title %}
{% block content %}
<link rel="stylesheet" href="{% static 'catalog/book_list.css' %}">
<link rel="stylesheet" href="user/user_borrowed.css">
<div class="container">
    <ul class='book-list'>
        {% if bookinstance_list %}
        {% for book in bookinstance_list %}
        <li class='book'>
            <a href="{{book.book.get_absolute_url}}">
                <img class='book-cover' src="https://source.unsplash.com/random/150x150?Book"
                    alt="{{book.book.title}} thumbnail">
                <div class="book-detail">
                    <a class="book-title" href="{{book.get_absolute_url}}">{{book.book.title}}</a>
                    <p class="book-subtitle"><small>By</small><a href="{{books.author.get_absolute_url}}"><em>
                                {{book.book.author.full_name}}</em></a></p>
                    <p class='info'>Due Back: <span class="info-item" {% if book.is_overdue %}style='color:red;'
                            {% else %}style='color:rgb(121, 202, 0);' {% endif %}>{{book.due_back}}</span> <span
                            class="info-item ren"><a href="{% url 'book_renewal' book.id %}">Renew</a></span></p>
                    <p class='info'>Borrower: <span class="info-item">{{book.borrower}}</span></p>
                    <p></p>
                </div>
            </a>
        </li>
        {% endfor %}
        {% else %}
        <li class='book'>
            <p>You haven't Borrowed any book {{user}}</p>
        </li>
        {% endif %}
    </ul>
</div>
{% endblock content %}

LocalLibrary/templates/user/user_borrowed.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Books{% endblock title %}
{% block content %}
<link rel="stylesheet" href="{% static 'catalog/book_list.css' %}">
<link rel="stylesheet" href="user/user_borrowed.css">
<div class="container">
    <ul class='book-list'>
        {% if bookinstance_list %}
        {% for book in bookinstance_list %}
        <li class='book'>
            <a href="{{book.book.get_absolute_url}}">
                <img class='book-cover' src="https://source.unsplash.com/random/150x150?Book"
                    alt="{{book.book.title}} thumbnail">
                <div class="book-detail">
                    <a class="book-title" href="{{book.get_absolute_url}}">{{book.book.title}}</a>
                    <p class="book-subtitle"><small>By</small><a href="{{books.author.get_absolute_url}}"><em>
                                {{book.book.author.full_name}}</em></a></p>
                    <p class='info'>Due Back: <small {% if book.is_overdue %}style='color:red;'{% else %}style='color:rgb(121, 202, 0);'{% endif %}>{{book.due_back}}</small></p>
                </div>
            </a>
        </li>
        {% endfor %}
        {% else %}
        <li class='book'>
            <p>You haven't Borrowed any book {{user}}</p>
        </li>
        {% endif %}
    </ul>
</div>
{% endblock content %}